## Повторение материала семинара 1

Работа с числами

In [ ]:
#сложение
15 + 5

In [ ]:
#вычитание
10 - 1

In [ ]:
#деление
10 / 2

In [ ]:
#умножение
5 * 15

In [ ]:
#возведение в степень
5**2

Основные типы данных

In [1]:
# str или строка
'здесь может быть любой текст'

'здесь может быть любой текст'

In [2]:
# int и float - числа
5 + 10.5

15.5

In [3]:
# list, set и tuple

[1, 2, 3, 4, 5]

[1, 2, 3, 4, 5]

In [4]:
{1, 2, 5, 2, 1, 6}

{1, 2, 5, 6}

In [5]:
(1,2,3,4,5)

(1, 2, 3, 4, 5)

In [7]:
# отличие list от tuple

a = [1,2,3,4,5]
b = (1,2,3,4,5)

In [8]:
a.append(6)
a

[1, 2, 3, 4, 5, 6]

In [9]:
a[0] = 100
a

[100, 2, 3, 4, 5, 6]

In [1]:
b.append(6)
b

NameError: name 'b' is not defined

In [11]:
b[0] = 100
b

TypeError: 'tuple' object does not support item assignment

In [ ]:
# dict - словарь
{'key1':100,'key2':150}

In [12]:
# вы можете проверить тип переменной
type(a)

list

Переменные

In [ ]:
# здесь мы присваиваем переменной x значение
x = 5

In [ ]:
x

In [ ]:
y = x + 10

In [ ]:
y

Логические выражения

<center> 
    <table>
        <tr>
            <th>Логическое выражение </th>
            <th> Значение </th>
        </tr> 
        <tr><td>&lt;</td><td> Меньше</td></tr>
        <tr><td>&gt;</td><td> Больше</td></tr>
        <tr><td>&lt;=</td><td> Меньше или равно</td></tr>
        <tr><td>&gt;=</td><td> Больше или равно</td></tr>
        <tr><td>==</td><td> Равно </td></tr>
        <tr><td>!=</td><td> Не равно</td></tr>
    </table>
</center>

In [ ]:
5 > 10

In [ ]:
6 <=15

In [ ]:
100 == 100

In [ ]:
'a' != 'b'

In [ ]:
'a' == 'a'

In [14]:
x = 4
if x < 5:
    print('less than 5')
else:
    print('no')

less than 5

Циклы

In [16]:
for i in [1,2,3,4,5]:
    print(i, end = ' ')

1 2 3 4 5

In [17]:
x = 5
while x != 0:
    print(x)
    x = x - 1

5
4
3
2
1

# Библиотека Pandas
 -  <a href="http://pandas.pydata.org/">Pandas</a> - библиотека для обработки и анализа данных.
 
Загрузка любой библиотеки выглядит следующим образом: <br /> 
**import** название [**as** псевдоним]

Обычно список импортируемых библиотек задается в самом начале ноутбука

In [18]:
import pandas as pd
#загрузили библиотеку и задали ее псевдоним, по которому далее к ней будем обращаться: pd

## Классы в Pandas

В пандас есть два типа структур данных:
- Series: одномерный массив с именованными индексами (чаще всего, данные одного типа)
- DataFrame: двухмерный массив, имеет табличную структуру, легко изменяется по размерам, может содержать в себе данные разных типов

Оба типа можно создавать вручную с помощью функций из самой библиотеки:
- pandas.Series(data=None, index=None, dtype=None)
- pandas.DataFrame(data=None, index=None, columns=None, dtype=None)

- **data** - данные, которые надо записать в структуру
- **index** - индексы строк
- **columns** - названия столбцов
- **dtype** - тип данных

Кроме data, остальные параметры опциональны

In [19]:
pd.Series([1, 2, 3, 5, 8, 13.5, 'asd', pd.datetime(2018, 1, 13)])

0                      1
1                      2
2                      3
3                      5
4                      8
5                   13.5
6                    asd
7    2018-01-13 00:00:00
dtype: object

In [20]:
#можно задать словарь
d = dict({
    'City': ['MSK', 'SPB', 'NN', 'SPB'],
    'Temperature': [-3, +2, -3, +2],
    'State': ['Cloudy', 'Clear', 'Snow', 'Clear'],
    'Date':[pd.datetime(2017, 1, 16), pd.datetime(2017, 1, 13), pd.datetime(2017, 3, 13), pd.datetime(2017, 1, 1)]
})

pd.DataFrame(d)

  City       Date   State  Temperature
0  MSK 2017-01-16  Cloudy           -3
1  SPB 2017-01-13   Clear            2
2   NN 2017-03-13    Snow           -3
3  SPB 2017-01-01   Clear            2

## Загрузка и запись данных
Функции типа .read_формат и 
.to_формат считывают и записывают данные соответственно. <br /> Полный список можно найти в документации:
http://pandas.pydata.org/pandas-docs/stable/io.html

Научимся считывать данные в формате csv (comma separated value) функцией:

- <a href="http://pandas.pydata.org/pandas-docs/stable/generated/pandas.read_csv.html#pandas.read_csv"> pd.read_csv()</a>: 

Аргументов у нее очень много, критически важные:
 - **filepath_or_buffer** - текстовая строка с названием (адресом) файла
 - **sep** - разделитель между данными
 - **header** - номер строки, в которой в файле указаны названия столбцов, None, если нет
 - **names** - список с названиями колонок
 - **index_col** - или номер столбца, или список,  или ничего - названия строк
 
 <a href="https://docs.google.com/spreadsheets/d/1tvaY9HyAyUwidqpZj11x_CVhlXHprnDog7JHou_3Tho/edit?usp=sharing"> Скачайте данные </a>

In [22]:
#Скорее всего, данные в папке загрузки. 
#Если текущий ноутбук лежит у вас на компьютере в папке, отличной от папки, куда загрузились данные, нужно указать полный путь
#Если оба файла в одной папке, достаточно указать FoodConsumptionInEurope.csv

foodCons = pd.read_csv('/Users/maximnemkevich/Documents/Data Science/Repo/2. Введение в Pandas/Датасет/FoodConsumptionInEurope.csv')
#Выведем на печать
foodCons

,Country,Albania,Austria,Belgium,Bulgaria,Czechoslovakia,Denmark,E_Germany,Finland,France,...,Norway,Poland,Portugal,Romania,Spain,Sweden,Switzerland,UK,USSR,W_Germany
0,RedMeat,10.1,8.9,13.5,7.8,9.7,10.6,8.4,9.5,18.0,...,9.4,6.9,6.2,6.2,7.1,9.9,13.1,17.4,9.3,11.4
1,WhiteMeat,1.4,14.0,9.3,6.0,11.4,10.8,11.6,4.9,9.9,...,4.7,10.2,3.7,6.3,3.4,7.8,10.1,5.7,4.6,12.5
2,Eggs,0.5,4.3,4.1,1.6,2.8,3.7,3.7,2.7,3.3,...,2.7,2.7,1.1,1.5,3.1,3.5,3.1,4.7,2.1,4.1
3,Milk,8.9,19.9,17.5,8.3,12.5,25.0,11.1,33.7,19.5,...,23.3,19.3,4.9,11.1,8.6,24.7,23.8,20.6,16.6,18.8
4,Fish,0.2,2.1,4.5,1.2,2.0,9.9,5.4,5.8,5.7,...,9.7,3.0,14.2,1.0,7.0,7.5,2.3,4.3,3.0,3.4
5,Cereals,42.3,28.0,26.6,56.7,34.3,21.9,24.6,26.3,28.1,...,23.0,36.1,27.0,49.6,29.2,19.5,25.6,24.3,43.6,18.6
6,Starch,0.6,3.6,5.7,1.1,5.0,4.8,6.5,5.1,4.8,...,4.6,5.9,5.9,3.1,5.7,3.7,2.8,4.7,6.4,5.2
7,Nuts,5.5,1.3,2.1,3.7,1.1,0.7,0.8,1.0,2.4,...,1.6,2.0,4.7,5.3,5.9,1.4,2.4,3.4,3.4,1.5
8,Fr&Veg,1.7,4.3,4.0,4.2,4.0,2.4,3.6,1.4,6.5,...,2.7,6.6,7.9,2.8,7.2,2.0,4.9,3.3,2.9,3.8

In [23]:
#Cчитаем так, чтобы первый столбец стал названием строк (индексом)
foodCons = pd.read_csv('/Users/maximnemkevich/Documents/Data Science/Repo/2. Введение в Pandas/Датасет/FoodConsumptionInEurope.csv', index_col = 0)
foodCons

,Albania,Austria,Belgium,Bulgaria,Czechoslovakia,Denmark,E_Germany,Finland,France,Greece,...,Norway,Poland,Portugal,Romania,Spain,Sweden,Switzerland,UK,USSR,W_Germany
Country,,,,,,,,,,,,,,,,,,,,,
RedMeat,10.1,8.9,13.5,7.8,9.7,10.6,8.4,9.5,18.0,10.2,...,9.4,6.9,6.2,6.2,7.1,9.9,13.1,17.4,9.3,11.4
WhiteMeat,1.4,14.0,9.3,6.0,11.4,10.8,11.6,4.9,9.9,3.0,...,4.7,10.2,3.7,6.3,3.4,7.8,10.1,5.7,4.6,12.5
Eggs,0.5,4.3,4.1,1.6,2.8,3.7,3.7,2.7,3.3,2.8,...,2.7,2.7,1.1,1.5,3.1,3.5,3.1,4.7,2.1,4.1
Milk,8.9,19.9,17.5,8.3,12.5,25.0,11.1,33.7,19.5,17.6,...,23.3,19.3,4.9,11.1,8.6,24.7,23.8,20.6,16.6,18.8
Fish,0.2,2.1,4.5,1.2,2.0,9.9,5.4,5.8,5.7,5.9,...,9.7,3.0,14.2,1.0,7.0,7.5,2.3,4.3,3.0,3.4
Cereals,42.3,28.0,26.6,56.7,34.3,21.9,24.6,26.3,28.1,41.7,...,23.0,36.1,27.0,49.6,29.2,19.5,25.6,24.3,43.6,18.6
Starch,0.6,3.6,5.7,1.1,5.0,4.8,6.5,5.1,4.8,2.2,...,4.6,5.9,5.9,3.1,5.7,3.7,2.8,4.7,6.4,5.2
Nuts,5.5,1.3,2.1,3.7,1.1,0.7,0.8,1.0,2.4,7.8,...,1.6,2.0,4.7,5.3,5.9,1.4,2.4,3.4,3.4,1.5
Fr&Veg,1.7,4.3,4.0,4.2,4.0,2.4,3.6,1.4,6.5,6.5,...,2.7,6.6,7.9,2.8,7.2,2.0,4.9,3.3,2.9,3.8

In [24]:
#транспонируем и применим метод head, чтобы посмотреть на первую строчку
foodCons = foodCons.transpose()
foodCons

Country,RedMeat,WhiteMeat,Eggs,Milk,Fish,Cereals,Starch,Nuts,Fr&Veg
Albania,10.1,1.4,0.5,8.9,0.2,42.3,0.6,5.5,1.7
Austria,8.9,14.0,4.3,19.9,2.1,28.0,3.6,1.3,4.3
Belgium,13.5,9.3,4.1,17.5,4.5,26.6,5.7,2.1,4.0
Bulgaria,7.8,6.0,1.6,8.3,1.2,56.7,1.1,3.7,4.2
Czechoslovakia,9.7,11.4,2.8,12.5,2.0,34.3,5.0,1.1,4.0
Denmark,10.6,10.8,3.7,25.0,9.9,21.9,4.8,0.7,2.4
E_Germany,8.4,11.6,3.7,11.1,5.4,24.6,6.5,0.8,3.6
Finland,9.5,4.9,2.7,33.7,5.8,26.3,5.1,1.0,1.4
France,18.0,9.9,3.3,19.5,5.7,28.1,4.8,2.4,6.5
Greece,10.2,3.0,2.8,17.6,5.9,41.7,2.2,7.8,6.5
Hungary,5.3,12.4,2.9,9.7,0.3,40.1,4.0,5.4,4.2
Ireland,13.9,10.0,4.7,25.8,2.2,24.0,6.2,1.6,2.9
Italy,9.0,5.1,2.9,13.7,3.4,36.8,2.1,4.3,6.7
Netherlands,9.5,13.6,3.6,23.4,2.5,22.4,4.2,1.8,3.7
Norway,9.4,4.7,2.7,23.3,9.7,23.0,4.6,1.6,2.7
Poland,6.9,10.2,2.7,19.3,3.0,36.1,5.9,2.0,6.6
Portugal,6.2,3.7,1.1,4.9,14.2,27.0,5.9,4.7,7.9
Romania,6.2,6.3,1.5,11.1,1.0,49.6,3.1,5.3,2.8
Spain,7.1,3.4,3.1,8.6,7.0,29.2,5.7,5.9,7.2
Sweden,9.9,7.8,3.5,24.7,7.5,19.5,3.7,1.4,2.0
Switzerland,13.1,10.1,3.1,23.8,2.3,25.6,2.8,2.4,4.9
UK,17.4,5.7,4.7,20.6,4.3,24.3,4.7,3.4,3.3
USSR,9.3,4.6,2.1,16.6,3.0,43.6,6.4,3.4,2.9
W_Germany,11.4,12.5,4.1,18.8,3.4,18.6,5.2,1.5,3.8

In [25]:
#Запишем в папку рядом с вашим ноутбуком переделанный файл
foodCons.to_csv('Food.csv')

## Просмотр данных
Методы:
- head(): первые записи
- tail(): последние записи
- describe(): таблича с описательными статистиками

In [ ]:
foodCons.head(1)

In [ ]:
foodCons.tail(3)

In [ ]:
foodCons.describe()

## Сортировка данных в таблице
Методы:
- sort_index - сортировка либо по столбцам, либо по строкам
- sort_values - сортировка по значению

In [26]:
foodCons.sort_index(axis = 'index', ascending = False)

Country,RedMeat,WhiteMeat,Eggs,Milk,Fish,Cereals,Starch,Nuts,Fr&Veg
W_Germany,11.4,12.5,4.1,18.8,3.4,18.6,5.2,1.5,3.8
USSR,9.3,4.6,2.1,16.6,3.0,43.6,6.4,3.4,2.9
UK,17.4,5.7,4.7,20.6,4.3,24.3,4.7,3.4,3.3
Switzerland,13.1,10.1,3.1,23.8,2.3,25.6,2.8,2.4,4.9
Sweden,9.9,7.8,3.5,24.7,7.5,19.5,3.7,1.4,2.0
Spain,7.1,3.4,3.1,8.6,7.0,29.2,5.7,5.9,7.2
Romania,6.2,6.3,1.5,11.1,1.0,49.6,3.1,5.3,2.8
Portugal,6.2,3.7,1.1,4.9,14.2,27.0,5.9,4.7,7.9
Poland,6.9,10.2,2.7,19.3,3.0,36.1,5.9,2.0,6.6
Norway,9.4,4.7,2.7,23.3,9.7,23.0,4.6,1.6,2.7
Netherlands,9.5,13.6,3.6,23.4,2.5,22.4,4.2,1.8,3.7
Italy,9.0,5.1,2.9,13.7,3.4,36.8,2.1,4.3,6.7
Ireland,13.9,10.0,4.7,25.8,2.2,24.0,6.2,1.6,2.9
Hungary,5.3,12.4,2.9,9.7,0.3,40.1,4.0,5.4,4.2
Greece,10.2,3.0,2.8,17.6,5.9,41.7,2.2,7.8,6.5
France,18.0,9.9,3.3,19.5,5.7,28.1,4.8,2.4,6.5
Finland,9.5,4.9,2.7,33.7,5.8,26.3,5.1,1.0,1.4
E_Germany,8.4,11.6,3.7,11.1,5.4,24.6,6.5,0.8,3.6
Denmark,10.6,10.8,3.7,25.0,9.9,21.9,4.8,0.7,2.4
Czechoslovakia,9.7,11.4,2.8,12.5,2.0,34.3,5.0,1.1,4.0
Bulgaria,7.8,6.0,1.6,8.3,1.2,56.7,1.1,3.7,4.2
Belgium,13.5,9.3,4.1,17.5,4.5,26.6,5.7,2.1,4.0
Austria,8.9,14.0,4.3,19.9,2.1,28.0,3.6,1.3,4.3
Albania,10.1,1.4,0.5,8.9,0.2,42.3,0.6,5.5,1.7

In [27]:
foodCons.sort_values(by = 'Milk', ascending = True)

Country,RedMeat,WhiteMeat,Eggs,Milk,Fish,Cereals,Starch,Nuts,Fr&Veg
Portugal,6.2,3.7,1.1,4.9,14.2,27.0,5.9,4.7,7.9
Bulgaria,7.8,6.0,1.6,8.3,1.2,56.7,1.1,3.7,4.2
Spain,7.1,3.4,3.1,8.6,7.0,29.2,5.7,5.9,7.2
Albania,10.1,1.4,0.5,8.9,0.2,42.3,0.6,5.5,1.7
Hungary,5.3,12.4,2.9,9.7,0.3,40.1,4.0,5.4,4.2
Romania,6.2,6.3,1.5,11.1,1.0,49.6,3.1,5.3,2.8
E_Germany,8.4,11.6,3.7,11.1,5.4,24.6,6.5,0.8,3.6
Czechoslovakia,9.7,11.4,2.8,12.5,2.0,34.3,5.0,1.1,4.0
Italy,9.0,5.1,2.9,13.7,3.4,36.8,2.1,4.3,6.7
USSR,9.3,4.6,2.1,16.6,3.0,43.6,6.4,3.4,2.9
Belgium,13.5,9.3,4.1,17.5,4.5,26.6,5.7,2.1,4.0
Greece,10.2,3.0,2.8,17.6,5.9,41.7,2.2,7.8,6.5
W_Germany,11.4,12.5,4.1,18.8,3.4,18.6,5.2,1.5,3.8
Poland,6.9,10.2,2.7,19.3,3.0,36.1,5.9,2.0,6.6
France,18.0,9.9,3.3,19.5,5.7,28.1,4.8,2.4,6.5
Austria,8.9,14.0,4.3,19.9,2.1,28.0,3.6,1.3,4.3
UK,17.4,5.7,4.7,20.6,4.3,24.3,4.7,3.4,3.3
Norway,9.4,4.7,2.7,23.3,9.7,23.0,4.6,1.6,2.7
Netherlands,9.5,13.6,3.6,23.4,2.5,22.4,4.2,1.8,3.7
Switzerland,13.1,10.1,3.1,23.8,2.3,25.6,2.8,2.4,4.9
Sweden,9.9,7.8,3.5,24.7,7.5,19.5,3.7,1.4,2.0
Denmark,10.6,10.8,3.7,25.0,9.9,21.9,4.8,0.7,2.4
Ireland,13.9,10.0,4.7,25.8,2.2,24.0,6.2,1.6,2.9
Finland,9.5,4.9,2.7,33.7,5.8,26.3,5.1,1.0,1.4

## Выбор данных из датафрейма

In [28]:
#Выбор по столбцу
#foodCons['RedMeat']
foodCons.RedMeat

Albania           10.1
Austria            8.9
Belgium           13.5
Bulgaria           7.8
Czechoslovakia     9.7
Denmark           10.6
E_Germany          8.4
Finland            9.5
France            18.0
Greece            10.2
Hungary            5.3
Ireland           13.9
Italy              9.0
Netherlands        9.5
Norway             9.4
Poland             6.9
Portugal           6.2
Romania            6.2
Spain              7.1
Sweden             9.9
Switzerland       13.1
UK                17.4
USSR               9.3
W_Germany         11.4
Name: RedMeat, dtype: float64

In [29]:
#Выбор по строкам
foodCons[0:2]

Country  RedMeat  WhiteMeat  Eggs  Milk  Fish  Cereals  Starch  Nuts  Fr&Veg
Albania     10.1        1.4   0.5   8.9   0.2     42.3     0.6   5.5     1.7
Austria      8.9       14.0   4.3  19.9   2.1     28.0     3.6   1.3     4.3

In [30]:
foodCons['Albania':'Belgium']

Country  RedMeat  WhiteMeat  Eggs  Milk  Fish  Cereals  Starch  Nuts  Fr&Veg
Albania     10.1        1.4   0.5   8.9   0.2     42.3     0.6   5.5     1.7
Austria      8.9       14.0   4.3  19.9   2.1     28.0     3.6   1.3     4.3
Belgium     13.5        9.3   4.1  17.5   4.5     26.6     5.7   2.1     4.0

In [31]:
#Выбор строки по названию (индексу)
foodCons.loc['Austria']

Country
RedMeat       8.9
WhiteMeat    14.0
Eggs          4.3
Milk         19.9
Fish          2.1
Cereals      28.0
Starch        3.6
Nuts          1.3
Fr&Veg        4.3
Name: Austria, dtype: float64

In [ ]:
#пара столбцов
foodCons.loc[:, ['RedMeat', 'Eggs']]

In [ ]:
#пара столбцов
foodCons.loc[['Austria','Belgium'], ['RedMeat', 'Eggs']]

In [ ]:
#выбор ячейки
foodCons.loc['Austria', 'RedMeat']

In [ ]:
#Выбор строки по номеру
foodCons.iloc[1]

In [ ]:
#Выбор одного элемента
foodCons.iloc[1,0]

In [ ]:
foodCons.iloc[0:3,1:4]

In [2]:
foodCons.iloc[:,1]

NameError: name 'foodCons' is not defined

In [ ]:
foodCons.iloc[1,:]

## Выбор с условием

Допустим, что нам нужны не только целом столбцы или "слайсы" данных, но данные, соответствующие определенным условиям

In [ ]:
foodCons[foodCons['RedMeat'] > 5]

In [ ]:
foodCons[foodCons['RedMeat'] > 5]['Eggs']

## Вставка столбцов и строк
Столбцы вставляются очень просто. 
Например, добавим столбец с регионами Европы

Европейские регионы: <br />
- Северная Европа: 0 <br />
- Южная Европа: 1 <br />
- Западная Европа: 2 <br />
- Восточная Европа: 3 <br />

In [ ]:
foodCons['Region'] = [1, 2, 2, 3, 3, 0, 2, 0, 2, 1, 3, 2, 1, 2, 0, 3, 1, 3, 1, 0, 2, 2, 3, 2]
foodCons

А строчки - методом append

In [ ]:
s = foodCons.iloc[3]
foodCons.append(s)

## Группировка данных
Метод groupby группирует по столбцу

In [ ]:
foodCons.groupby('Region').sum()

## Задача
Скачайте данные по <a href=https://www.dropbox.com/s/f2e3afgxw90qluw/yob2015.txt?dl=0>ссылке</a>. <br />
В файле представлена информация об именах новорожденных в США в 2015 году в формате: "name, gender, count"

0. Данные в формате .txt, но отлично считываются изученной функцией для чтения :)
1. Укажите наименования заголовков Name, Gender, Count
2. Выведите первые 10 строк
3. Посчитайте, сколько всего новорожденных
4. Посчитайте, сколько новорожденных девочек
5. Посчитайте долю девочек среди новорожденных

In [ ]:
#1
# используйте функцию pd.read_csv('здесь укажите название файла', header=None). Запишите датафрейм в переменную df

In [ ]:
#2
# Переименовать колонки в датафрейме просто, ниже подсказка. Перечислите в квадратных скобках нужные названия
df.columns = []

df.columns

In [ ]:
#3
# Помните функции, которые в секции "Просмотр данных"?

In [ ]:
#4
# Как вариант решения задачи - применить функцию .sum() к нужной колонке датафрейма

In [ ]:
#5
# Повторите предыдущий пункт, предварительно добавив фильтр по колонке Gender

In [ ]:
#6
# Вы почти у цели

# Итоги

## Библиотека pandas:

###  Функции для создания объектов
- pd.Series()
- pd.DataFrame()
- pd.read_csv()
- pd.isna()

### Методы
- pd.DataFrame.transpose()
- pd.DataFrame.head()
- pd.DataFrame.tail()
- pd.DataFrame.rename()
- pd.DataFrame.loc()
- pd.DataFrame.iloc()
- pd.DataFrame.fillna()
- pd.DataFrame.dropna()
- pd.DataFrame.append()
- pd.DataFrame.sum()